remote: origin
git_root: .
master: "main"
develop: "main"
patch_prefix: .
preserve_patch_zero: true
do_version_commit: false
create_tags: patch
push_develop: no
push_master: yes
push_tags: yes
vesion_file: composer.json
version: 0.0.2
